### ISSUE TITLE
cata lua error 

### ISSUE THREAD

**Issue by crossfactioninstancedpvp** [a3st/sArena#3]
697x sArena/Modules/Auras.lua:532: attempt to compare number with nil
[string "@sArena/Modules/Auras.lua"]:532: in function `FindAura'
[string "@sArena/sArena.lua"]:296: in function <sArena/sArena.lua:283>

Locals:
self = sArenaEnemyFrame3 {
 0 = <userdata>
 Charge = Frame {
 }
 RandomRoot = Frame {
 }
 class = "PRIEST"
 FindAura = <function> defined @sArena/Modules/Auras.lua:512
 MindControl = Frame {
 }
 UpdateStatusTextVisible = <function> defined @sArena/sArena.lua:556
 PowerText = FontString {
 }
 ResetLayout = <function> defined @sArena/sArena.lua:461
 Horror = Frame {
 }
 healthbar = StatusBar {
 }
 TexturePool = <table> {
 }
 ClassIconMask = MaskTexture {
 }
 UpdateClassIcon = <function> defined @sArena/Modules/Auras.lua:487
 Cyclone = Frame {
 }
 Disarm = Frame {
 }
 HealthText = FontString {
 }
 unit = "arena3"
 CastBar = StatusBar {
 }
 currentClassIconTexture = 136018
 Fear = Frame {
 }
 ResetRacial = <function> defined @sArena/Modules/Racials.lua:105
 ResetTrinket = <function> defined @sArena/Modules/Trinkets.lua:22
 OnLoad = <function> defined @sArena/sArena.lua:253
 UpdateTrinket = <function> defined @sArena/Modules/Trinkets.lua:11
 Trinket = Frame {
 }
 UpdatePlayer = <function> defined @sArena/sArena.lua:367
 FindRacial = <function> defined @sArena/Modules/Racials.lua:63
 Name = FontString {
 }
 FindSpec = <function> defined @sArena/Modules/Specs.lua:179
 GetClass = <function> defined @sArena/sArena.lua:431
 UpdateSpecIcon = <function> defined @sArena/Modules/Specs.lua:175
 currentInterruptDuration = 2
 parent = sArena {
 }
 currentInterruptTexture = 136018
 currentClassIconStartTime = 26621.688000
 UpdateDRPositions = <function> defined @sArena/Modules/DiminishingReturns.lua:102
 currentInterruptSpellID = 57994
 currentAuraTexture = 136018
 currentAuraSpellID = 57994
 SetLifeState = <function> defined @sArena/sArena.lua:518
 Silence = Frame {
 }
 Scatter = Frame {
 }
 race = "Scourge"
 ClassIconCooldown = Cooldown {
 }
 Initialize = <function> defined @sArena/sArena.lua:344
 SetMysteryPlayer = <function> defined @sArena/sArena.lua:414
 specTexture = 135940
 Racial = Frame {
 }
 FindInterrupt = <function> defined @sArena/Modules/Auras.lua:462
 currentAuraDuration = 2
 DeathIcon = Texture {
 }
 FindTrinket = <function> defined @sArena/Modules/Trinkets.lua:1
 hideStatusText = false
 OnLeave = <function> defined @sArena/sArena.lua:361
 SpecIcon = Frame {
 }
 SetPowerType = <function> defined @sArena/sArena.lua:511
 PowerBar = StatusBar {
 }
 Incapacitate = Frame {
 }
 currentInterruptExpirationTime = 26623.688000
 CounterAttack = Frame {
 }
 HealthBar = StatusBar {
 }
 RandomStun = Frame {
 }
 Root = Frame {
 }
 SetStatusText = <function> defined @sArena/sArena.lua:529
 Stun = Frame {
 }
 OnEvent = <function> defined @sArena/sArena.lua:283
 currentHealth = 124001
 OpenerStun = Frame {
 }
 ResetDR = <function> defined @sArena/Modules/DiminishingReturns.lua:133
 UpdateRacial = <function> defined @sArena/Modules/Racials.lua:90
 OnEnter = <function> defined @sArena/sArena.lua:354
 currentAuraStartTime = 26621.688000
 FindDR = <function> defined @sArena/Modules/DiminishingReturns.lua:50
 ClassIcon = Texture {
 }
}
unit = "arena3"
currentSpellID = 57994
currentDuration = 2
currentExpirationTime = 26623.688000
currentTexture = 136018
(for index) = 2
(for limit) = 2
(for step) = 1
i = 2
filter = "HARMFUL"
(for index) = 2
(for limit) = 30
(for step) = 1
n = 2
_ = "Hammer of Justice"
texture = 135963
_ = 0
_ = "Magic"
duration = 6
expirationTime = 26628.311000
_ = "player"
_ = false
_ = false
spellID = 853
(*temporary) = 18
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
auraList = <table> {
 47585 = 139
 20511 = 108
 4511 = 153
 18499 = 277
 16188 = 283
 19577 = 32
 28272 = 115
 1776 = 94
 1777 = 99
 8122 = 116
 8124 = 119
 3045 = 262
 5573 = 142
 1020

**Comment by a3st** [comment]
Temporary fix there https://github.com/a3st/sArena/blob/a0f7f9b548b61fcdaa4c539f7e87049b03373a72/sArena/Modules/Auras.lua
Try it and let me know how it works. The next update on CurseForge will be when I remove spell ranks from all tables.
